### ISSUE TITLE
能否有个使用说明？

### ISSUE THREAD

**Issue by kenpt** [ZhaoMeng0918/Spider_GongZhongHao#1]
我想学习使用文章爬取方法，可否有个简明的使用方法？

**Comment by ZhaoMeng0918** [comment]
抱歉，我才看到，我明天写一个使用教程给你。



在 2022-03-14 10:23:51，"kenpt" ***@***.***> 写道：

我想学习使用文章爬取方法，可否有个简明的使用方法？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZhaoMeng8959** [comment]
你好，我已经讲配置文件的说明添加进去了，你可以看一下README.md。程序比较简单，里面也已经添加了部分注释。
