### ISSUE TITLE
文件存储问题

### ISSUE THREAD

**Issue by FowlieRini** [ZhaoMeng0918/Spider_GongZhongHao#2]
下载的文章只能是txt吗？如果存数据库后能不能恢复成网页访问的样子。

**Comment by ZhaoMeng8959** [comment]
类似于这篇文章：[微信公众号文章](http://mp.weixin.qq.com/s?__biz=MjM5MzM5MTMwMQ==&mid=2651645736&idx=1&sn=d7df8ce9413e73aefd11e02bc17a35a3&chksm=bd6ff0828a1879949fca57ce82764e6272f3d68fd0ddc30ed001689a40f04fa828d38ace9765#rd)
你可以根据XPATH找到这个节点：//*[@id="page-content"]，如果想要恢复成网页的样子，可以把该节点以及其子节点的html代码全部保存到数据库或文件即可。

**Comment by chaoinchina** [comment]
大佬能留个微吗 我目前用的是中间人代理开发不稳定，想咨询您下

**Comment by chaoinchina** [comment]
等待 da lao

**Comment by ZhaoMeng8959** [comment]
15991808959，你加我，抱歉，我们实验室最近前5天封了，我没电脑，所以没看到。
