### ISSUE TITLE
read timeout

### ISSUE THREAD

**Issue by 15235007059** [ZhaoMeng0918/Spider_GongZhongHao#3]
作者您好，我想请问一下在爬取微信公众号文章的时候第一篇爬取成功，第二篇的时候显示read timeout ，我把原来的参数改成60、90、120显示的是同样的timeout 是微信反扒机制的原因吗？

**Comment by ZhaoMeng8959** [comment]
就爬了一篇不会触发反爬机制的。

**Comment by 15235007059** [comment]
那有可能是什么原因呢？我这边每次都是timeout😂



| |
axiaoxiao_110
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月29日 16:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ZhaoMeng0918/Spider_GongZhongHao] read timeout (Issue #3) |

就爬了一篇不会触发反爬机制的。

**Comment by ZhaoMeng8959** [comment]
你可以加我微信，15991808959，我帮你看看。
